//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalLuz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aluguere
    {
        public int idalu { get; set; }
        public Nullable<int> idcli { get; set; }
        public Nullable<int> idcar { get; set; }
        public Nullable<System.DateTime> datainicial { get; set; }
        public Nullable<System.DateTime> datafinal { get; set; }
        public Nullable<int> duracao { get; set; }
        public Nullable<decimal> custo { get; set; }
    
        public virtual carro carro { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
