//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalLuz.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.alugueres = new HashSet<aluguere>();
        }
    
        public int Idcli { get; set; }
        public string nome { get; set; }
        [DataType(DataType.Date,ErrorMessage ="Erro na Data")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d/mm/yyyy}")]
        public Nullable<System.DateTime> datanasc { get; set; }
        public Nullable<int> idade { get; set; }
        public string fotopath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aluguere> alugueres { get; set; }
    }
}
