//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalLuz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StandTintIII_MBEntities : DbContext
    {
        public StandTintIII_MBEntities()
            : base("name=StandTintIII_MBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aluguere> alugueres { get; set; }
        public virtual DbSet<carro> carros { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<marca> marcas { get; set; }
    }
}
